# Generated by Django 6.0.3 on 2026-03-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pensioner',
            field=models.BooleanField(default=False, verbose_name='Подтверждённый пенсионер'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pensioner_pending',
            field=models.BooleanField(default=False, verbose_name='Ожидает подтверждения'),
        ),
        migrations.AddField(
            model_name='user',
            name='pensioner_promo_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Промокод пенсионера'),
        ),
    ]
